---
- hosts: local
  connection: local

  tasks:
    - name: Create our test vm
      qubesos:
        guest: supansible
        label: blue
        state: present
        template: "debian-9"

    - name: Get it up and running
      qubesos:
        guest: supansible
        state: running



