---
- hosts: local
  connection: local

  tasks:
    - name: Create our test vm
      qubesos:
        guest: supansible
        label: blue
        state: present
        template: "debian-9"
        command: create

    - name: Get it up and running
      qubesos:
        guest: supansible
        state: running

    - name: Create our xchat
      qubesos:
        guest: xchat
        label: blue
        template: "fedora-28"
        command: create


