---
- hosts: local
  connection: local

  tasks:
    - name: Make sure the VM is present
      qubesos:
        guest: xchat2
        state: present
        properties:
          memory: 1200
          maxmem: 2400
          netvm: 'sys-whonix'
          label: "yellow"

    - name: Run the VM
      qubesos:
        guest: xchat2
        state: running


