---
- hosts: local
  connection: local
  tasks:
    - name: Make sure the VM is present
      qubesos:
        guest: xchat
        state: present
        properties:
          memory: 1200
          maxmem: 2400
          netvm: 'sys-whonix'
          label: "yellow"
          volume:
            name: "private"
            size: "5368709120"

    - name: Run the VM
      qubesos:
        guest: xchat
        state: running
