---
- hosts: local
  connection: local

  tasks:
    - name: Make sure the VM is present
      qubesos:
        guest: xchat2
        state: present
        preferences:
          memory: 1200
          maxmem: 2400
          netvm: 'sys-firewall'
          #default_dispvm: 'fedora-25-dvm'
          #template: fedora-28
          label: "blue"
    - name: Run the VM
      qubesos:
        guest: xchat
        state: running


